import { ListingSrService } from '@listingSr/core/services/listingSrService';
import { IListingSrRepository } from '@listingSr/core/interfaces/listingSrRepository';
import { PriceEstimatorService } from '@listingSr/core/services/priceEstimatorService';
import { SrAnalyticsService } from '@listingSr/core/services/analytics/srAnalyticsService';
import { ISrAnalyticsService } from '@listingSr/core/interfaces/srAnalyticsService';
import { BoundingBoxService } from '@shared/services/boundingBoxService';
import { IGeoSpatialService } from './geoSpatialService';
import { ISrCacheService } from './srCacheService';
import { AnalyticsManagerService } from '@shared/services/analyticsManagerService';
import { LocationChangeUseCase } from '@searchResult/useCases/locationChange/locationChange.usecase';
import { SaveSearchUseCase } from '@searchResult/useCases/saveSearch/saveSearch.usecase';
import { DeleteNoteUseCase } from '@searchResult/useCases/note/deleteNote.usecase';
import { SaveNoteUseCase } from '@searchResult/useCases/note/saveNote.usecase';
import { AddShortlistUseCase } from '@searchResult/useCases/shortlistProperty/addShortlist.usecase';
import { RemoveShortlistUseCase } from '@searchResult/useCases/shortlistProperty/removeShortlist.usecase';
import { ApplyFiltersUseCase } from '@searchResult/useCases/filters/applyFilters.usecase';
import { ApplySortUseCase } from '@searchResult/useCases/sort/applySort.usecase';
import { PageChangeUseCase } from '@searchResult/useCases/pageChange/pageChange.useCase';
import { AddPropertyToCompareUseCase } from '@searchResult/useCases/compareProperty/addPropertyToCompare.usecase';
import { RemovePropertyFromCompareUseCase } from '@searchResult/useCases/compareProperty/removePropertyFromCompare.usecase';
import { RemoveAllPropertyFromCompareUseCase } from '@searchResult/useCases/compareProperty/removeAllPropertyFromCompare.usecase';
import { CreateNewCompareGroupUseCase } from '@searchResult/useCases/compareProperty/createNewCompareGroup.usecase';
import { GetCompareGroupsListUseCase } from '@searchResult/useCases/compareProperty/getCompareGroupsList.usecase';
import { SavePropertiesToCompareGroupUseCase } from '@searchResult/useCases/compareProperty/savePropertiesToCompareGroup.usecase';
import { OffSeeAllToggleUseCase } from '@searchResult/useCases/seeAllToggle/offSeeAllToggle.usecase';
import { OnSeeAllToggleUseCase } from '@searchResult/useCases/seeAllToggle/onSeeAllToggle.usecase';
import { SendEnquiryUseCase } from '@searchResult/useCases/sendEnquiry/sendEnquiry.usecase';
import { MapPanUseCase } from '@searchResult/useCases/mapPan/mapPan.usecase';
import { MapZoomInUseCase } from '@searchResult/useCases/mapZoom/mapZoomIn.usecase';
import { MapZoomOutUseCase } from '@searchResult/useCases/mapZoom/mapZoomOut.usecase';
import { MarkerClickUseCase } from '@searchResult/useCases/markerClick/markerClick.usecase';
import { SrViewService } from '@searchResult/services/srView.service';

// Define the types of services you want to provide
export interface IServiceContext {
	srCacheService: ISrCacheService;
	listingSrService: ListingSrService;
	geoSpatialService: IGeoSpatialService;
	listingSrRepository: IListingSrRepository;
	priceEstimatorService: PriceEstimatorService;
	srAnalyticsService: SrAnalyticsService;
	listingSrServiceWithNullAnalyticsService: ListingSrService;
	nullListingSrAnalyticsService: ISrAnalyticsService;
	boundingBoxService: BoundingBoxService;
	srViewService: SrViewService;
	analyticsManagerService: AnalyticsManagerService;
	locationChangeUseCase: LocationChangeUseCase;
	saveSearchUseCase: SaveSearchUseCase;
	addShortlistUseCase: AddShortlistUseCase;
	removeShortlistUseCase: RemoveShortlistUseCase;
	deleteNoteUseCase: DeleteNoteUseCase;
	saveNoteUseCase: SaveNoteUseCase;
	filtersUseCase: ApplyFiltersUseCase;
	sortUseCase: ApplySortUseCase;
	pageChangeUseCase: PageChangeUseCase;
	addPropertyToCompareUseCase: AddPropertyToCompareUseCase;
	removePropertyFromCompareUseCase: RemovePropertyFromCompareUseCase;
	removeAllPropertiesFromCompareUseCase: RemoveAllPropertyFromCompareUseCase;
	savePropertiesToCompareGroupUseCase: SavePropertiesToCompareGroupUseCase;
	createNewCompareGroupUseCase: CreateNewCompareGroupUseCase;
	getCompareGroupsListUseCase: GetCompareGroupsListUseCase;
	offSeeAllToggleUseCase: OffSeeAllToggleUseCase;
	onSeeAllToggleUseCase: OnSeeAllToggleUseCase;
	sendEnquiryUseCase: SendEnquiryUseCase;
	mapPanUseCase: MapPanUseCase;
	mapZoomInUseCase: MapZoomInUseCase;
	mapZoomOutUseCase: MapZoomOutUseCase;
	markerClickUseCase: MarkerClickUseCase;
}
